In [23]:
from keras import Sequential, Input
from keras.layers import SimpleRNN, Dense
import pandas as pd
import numpy as np

In [25]:
data = {
    "word1" : ["movie", "movie", "movie"],
    "word2" : ["was", "was", "was"],
    "word3" : ["good", "bad", "not"],
    "word4" : ["", "", "good"],
    "sentiment" : ["positive", "negative", "negative"]
}

df = pd.DataFrame(data)

df

word1 word2 word3 word4 sentiment
0  movie   was  good        positive
1  movie   was   bad        negative
2  movie   was   not  good  negative

In [20]:
model = Sequential()

# Input layer shape is 3, 5 (3 rows, 5 cols matrix)
# shape : (timesteps=3, features=5)
model.add(Input(shape=(3, 5)))
model.add(SimpleRNN(3, activation="tanh")) # RNN with 3 units
model.add(Dense(1, activation="sigmoid"))

model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_2 (SimpleRNN)        │ (None, 3)              │            27 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 31 (124.00 B)

 Trainable params: 31 (124.00 B)

 Non-trainable params: 0 (0.00 B)

In [21]:
print(model.get_weights()[0].shape)
for i, _ in enumerate(model.get_weights()):
    print(model.get_weights()[i])

(5, 3)
[[-0.4918298  -0.10395205 -0.5497172 ]
 [ 0.5371204  -0.29212052 -0.459363  ]
 [-0.07216209  0.27675182  0.57008404]
 [-0.5917987   0.48053473 -0.47785464]
 [ 0.6610914  -0.25283486 -0.21055943]]
[[ 0.5157652   0.36359608  0.7757475 ]
 [-0.64255476 -0.43473667  0.6309734 ]
 [-0.5666653   0.8238944  -0.00940838]]
[0. 0. 0.]
[[-0.63016355]
 [-1.0444577 ]
 [ 0.02188528]]
[0.]
